#!@busybox@/bin/sh
export PATH=@path@

mount -t proc none /proc
mount -o remount,rw /

# devpts is required for virtual pty's to work. They are used by sshd(8).
mkdir -p /dev/pts
mount -t devpts none /dev/pts
mount -t sysfs none /sys

# nix-sys creates directory in /boot, so it has to be mounted
mount /dev/sda1 /boot

# Any now figure out path to nix-sys. Due chicken-and-egg problem we can't
# embed path to it into the script itself, like it is done in most cases.
set -- $(cat /proc/cmdline)
for arg ; do
	case "$arg" in
	(nix-sys=*) exec ${arg#nix-sys=}/bin/nix-sys ;;
	esac
done

# This should not be necessary, but helps with debugging if things go wrong.
exec /bin/sh
